name: pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
 job01:
   if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
   runs-on: [ubuntu-latest]
   steps:
     - name: getname
       if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
       run: |
         echo say hello ${{github.event.comment.body}}
         BODY=$(echo ${{github.event.comment.body}})
         NAME=$BODY[0]
         echo Name $NAME
         echo "::set-output name=fruit::strawberry"
     - name: test
       if: contains(github.event.comment.body, '/test')  # check the comment if it contains the keywords
       run: |
         echo "${{steps.getname.outputs.NAME}}"
         echo test
     - name: final
       run: |
         echo "${{steps.getname.outputs.fruit}}"
         echo final
